#!/usr/bin/php
<?php

require_once './vendor/autoload.php';

use App\Core\App;
use App\Core\Helpers\Cli\Cli;

#Register system paths
App::registerPath();

#Listen for command line tools
$cli = new Cli();
$cli->listen();